//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Uuid
{
    public class MUniqueID : Message
    {
        public const string RosMessageName = "uuid_msgs/UniqueID";

        //  A universally unique identifier (UUID).
        // 
        //   http://en.wikipedia.org/wiki/Universally_unique_identifier
        //   http://tools.ietf.org/html/rfc4122.html
        public byte[] uuid;

        public MUniqueID()
        {
            this.uuid = new byte[16];
        }

        public MUniqueID(byte[] uuid)
        {
            this.uuid = uuid;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            Array.Resize(ref uuid, 16);
            listOfSerializations.Add(this.uuid);

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            this.uuid= new byte[16];
            for(var i = 0; i < 16; i++)
            {
                this.uuid[i] = data[offset];
                offset += 1;
            }

            return offset;
        }

        public override string ToString()
        {
            return "MUniqueID: " +
            "\nuuid: " + System.String.Join(", ", uuid.ToList());
        }
    }
}
