//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Uuid
{
    [Serializable]
    public class UniqueIDMsg : Message
    {
        public const string k_RosMessageName = "uuid_msgs/UniqueID";
        public override string RosMessageName => k_RosMessageName;

        //  A universally unique identifier (UUID).
        // 
        //   http://en.wikipedia.org/wiki/Universally_unique_identifier
        //   http://tools.ietf.org/html/rfc4122.html
        public byte[] uuid;

        public UniqueIDMsg()
        {
            this.uuid = new byte[16];
        }

        public UniqueIDMsg(byte[] uuid)
        {
            this.uuid = uuid;
        }

        public static UniqueIDMsg Deserialize(MessageDeserializer deserializer) => new UniqueIDMsg(deserializer);

        private UniqueIDMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.uuid, sizeof(byte), 16);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.uuid);
        }

        public override string ToString()
        {
            return "UniqueIDMsg: " +
            "\nuuid: " + System.String.Join(", ", uuid.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
