//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class GeoPoseMsg : Message
    {
        public const string k_RosMessageName = "geographic_msgs/GeoPose";
        public override string RosMessageName => k_RosMessageName;

        //  Geographic pose, using the WGS 84 reference ellipsoid.
        // 
        //  Orientation uses the East-North-Up (ENU) frame of reference.
        //  (But, what about singularities at the poles?)
        public GeoPointMsg position;
        public Geometry.QuaternionMsg orientation;

        public GeoPoseMsg()
        {
            this.position = new GeoPointMsg();
            this.orientation = new Geometry.QuaternionMsg();
        }

        public GeoPoseMsg(GeoPointMsg position, Geometry.QuaternionMsg orientation)
        {
            this.position = position;
            this.orientation = orientation;
        }

        public static GeoPoseMsg Deserialize(MessageDeserializer deserializer) => new GeoPoseMsg(deserializer);

        private GeoPoseMsg(MessageDeserializer deserializer)
        {
            this.position = GeoPointMsg.Deserialize(deserializer);
            this.orientation = Geometry.QuaternionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.orientation);
        }

        public override string ToString()
        {
            return "GeoPoseMsg: " +
            "\nposition: " + position.ToString() +
            "\norientation: " + orientation.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
