//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Geographic
{
    public class MGeoPointStamped : Message
    {
        public const string RosMessageName = "geographic_msgs/GeoPointStamped";

        public MHeader header;
        public MGeoPoint position;

        public MGeoPointStamped()
        {
            this.header = new MHeader();
            this.position = new MGeoPoint();
        }

        public MGeoPointStamped(MHeader header, MGeoPoint position)
        {
            this.header = header;
            this.position = position;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.AddRange(position.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            offset = this.position.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MGeoPointStamped: " +
            "\nheader: " + header.ToString() +
            "\nposition: " + position.ToString();
        }
    }
}
