//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    public class MGeoPath : Message
    {
        public const string RosMessageName = "geographic_msgs/GeoPath";

        public Std.MHeader header;
        public MGeoPoseStamped[] poses;

        public MGeoPath()
        {
            this.header = new Std.MHeader();
            this.poses = new MGeoPoseStamped[0];
        }

        public MGeoPath(Std.MHeader header, MGeoPoseStamped[] poses)
        {
            this.header = header;
            this.poses = poses;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            
            listOfSerializations.Add(BitConverter.GetBytes(poses.Length));
            foreach(var entry in poses)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            
            var posesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.poses= new MGeoPoseStamped[posesArrayLength];
            for(var i = 0; i < posesArrayLength; i++)
            {
                this.poses[i] = new MGeoPoseStamped();
                offset = this.poses[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MGeoPath: " +
            "\nheader: " + header.ToString() +
            "\nposes: " + System.String.Join(", ", poses.ToList());
        }
    }
}
