//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Geographic
{
    public class MRouteNetwork : Message
    {
        public const string RosMessageName = "geographic_msgs/RouteNetwork";

        //  Geographic map route network.
        // 
        //  A directed graph of WayPoint nodes and RouteSegment edges.  This
        //  information is extracted from the more-detailed contents of a
        //  GeographicMap.  A RouteNetwork contains only the way points and
        //  route segments of interest for path planning.
        public MHeader header;
        public Uuid.MUniqueID id;
        //  This route network identifier
        public MBoundingBox bounds;
        //  2D bounding box for network
        public MWayPoint[] points;
        //  Way points in this network
        public MRouteSegment[] segments;
        //  Directed edges of this network
        public MKeyValue[] props;
        //  Network key/value properties

        public MRouteNetwork()
        {
            this.header = new MHeader();
            this.id = new Uuid.MUniqueID();
            this.bounds = new MBoundingBox();
            this.points = new MWayPoint[0];
            this.segments = new MRouteSegment[0];
            this.props = new MKeyValue[0];
        }

        public MRouteNetwork(MHeader header, Uuid.MUniqueID id, MBoundingBox bounds, MWayPoint[] points, MRouteSegment[] segments, MKeyValue[] props)
        {
            this.header = header;
            this.id = id;
            this.bounds = bounds;
            this.points = points;
            this.segments = segments;
            this.props = props;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.AddRange(id.SerializationStatements());
            listOfSerializations.AddRange(bounds.SerializationStatements());
            
            listOfSerializations.Add(BitConverter.GetBytes(points.Length));
            foreach(var entry in points)
                listOfSerializations.Add(entry.Serialize());
            
            listOfSerializations.Add(BitConverter.GetBytes(segments.Length));
            foreach(var entry in segments)
                listOfSerializations.Add(entry.Serialize());
            
            listOfSerializations.Add(BitConverter.GetBytes(props.Length));
            foreach(var entry in props)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            offset = this.id.Deserialize(data, offset);
            offset = this.bounds.Deserialize(data, offset);
            
            var pointsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.points= new MWayPoint[pointsArrayLength];
            for(var i = 0; i < pointsArrayLength; i++)
            {
                this.points[i] = new MWayPoint();
                offset = this.points[i].Deserialize(data, offset);
            }
            
            var segmentsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.segments= new MRouteSegment[segmentsArrayLength];
            for(var i = 0; i < segmentsArrayLength; i++)
            {
                this.segments[i] = new MRouteSegment();
                offset = this.segments[i].Deserialize(data, offset);
            }
            
            var propsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.props= new MKeyValue[propsArrayLength];
            for(var i = 0; i < propsArrayLength; i++)
            {
                this.props[i] = new MKeyValue();
                offset = this.props[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MRouteNetwork: " +
            "\nheader: " + header.ToString() +
            "\nid: " + id.ToString() +
            "\nbounds: " + bounds.ToString() +
            "\npoints: " + System.String.Join(", ", points.ToList()) +
            "\nsegments: " + System.String.Join(", ", segments.ToList()) +
            "\nprops: " + System.String.Join(", ", props.ToList());
        }
    }
}
