//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class RouteNetworkMsg : Message
    {
        public const string k_RosMessageName = "geographic_msgs/RouteNetwork";
        public override string RosMessageName => k_RosMessageName;

        //  Geographic map route network.
        // 
        //  A directed graph of WayPoint nodes and RouteSegment edges.  This
        //  information is extracted from the more-detailed contents of a
        //  GeographicMap.  A RouteNetwork contains only the way points and
        //  route segments of interest for path planning.
        public HeaderMsg header;
        public Uuid.UniqueIDMsg id;
        //  This route network identifier
        public BoundingBoxMsg bounds;
        //  2D bounding box for network
        public WayPointMsg[] points;
        //  Way points in this network
        public RouteSegmentMsg[] segments;
        //  Directed edges of this network
        public KeyValueMsg[] props;
        //  Network key/value properties

        public RouteNetworkMsg()
        {
            this.header = new HeaderMsg();
            this.id = new Uuid.UniqueIDMsg();
            this.bounds = new BoundingBoxMsg();
            this.points = new WayPointMsg[0];
            this.segments = new RouteSegmentMsg[0];
            this.props = new KeyValueMsg[0];
        }

        public RouteNetworkMsg(HeaderMsg header, Uuid.UniqueIDMsg id, BoundingBoxMsg bounds, WayPointMsg[] points, RouteSegmentMsg[] segments, KeyValueMsg[] props)
        {
            this.header = header;
            this.id = id;
            this.bounds = bounds;
            this.points = points;
            this.segments = segments;
            this.props = props;
        }

        public static RouteNetworkMsg Deserialize(MessageDeserializer deserializer) => new RouteNetworkMsg(deserializer);

        private RouteNetworkMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.id = Uuid.UniqueIDMsg.Deserialize(deserializer);
            this.bounds = BoundingBoxMsg.Deserialize(deserializer);
            deserializer.Read(out this.points, WayPointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.segments, RouteSegmentMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.props, KeyValueMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.id);
            serializer.Write(this.bounds);
            serializer.WriteLength(this.points);
            serializer.Write(this.points);
            serializer.WriteLength(this.segments);
            serializer.Write(this.segments);
            serializer.WriteLength(this.props);
            serializer.Write(this.props);
        }

        public override string ToString()
        {
            return "RouteNetworkMsg: " +
            "\nheader: " + header.ToString() +
            "\nid: " + id.ToString() +
            "\nbounds: " + bounds.ToString() +
            "\npoints: " + System.String.Join(", ", points.ToList()) +
            "\nsegments: " + System.String.Join(", ", segments.ToList()) +
            "\nprops: " + System.String.Join(", ", props.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
