//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class WayPointMsg : Message
    {
        public const string k_RosMessageName = "geographic_msgs/WayPoint";
        public override string RosMessageName => k_RosMessageName;

        //  Way-point element for a geographic map.
        public Uuid.UniqueIDMsg id;
        //  Unique way-point identifier
        public GeoPointMsg position;
        //  Position relative to WGS 84 ellipsoid
        public KeyValueMsg[] props;
        //  Key/value properties for this point

        public WayPointMsg()
        {
            this.id = new Uuid.UniqueIDMsg();
            this.position = new GeoPointMsg();
            this.props = new KeyValueMsg[0];
        }

        public WayPointMsg(Uuid.UniqueIDMsg id, GeoPointMsg position, KeyValueMsg[] props)
        {
            this.id = id;
            this.position = position;
            this.props = props;
        }

        public static WayPointMsg Deserialize(MessageDeserializer deserializer) => new WayPointMsg(deserializer);

        private WayPointMsg(MessageDeserializer deserializer)
        {
            this.id = Uuid.UniqueIDMsg.Deserialize(deserializer);
            this.position = GeoPointMsg.Deserialize(deserializer);
            deserializer.Read(out this.props, KeyValueMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.position);
            serializer.WriteLength(this.props);
            serializer.Write(this.props);
        }

        public override string ToString()
        {
            return "WayPointMsg: " +
            "\nid: " + id.ToString() +
            "\nposition: " + position.ToString() +
            "\nprops: " + System.String.Join(", ", props.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
