//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MCommandVtolTransitionRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/CommandVtolTransition";

        //  MAVLink command: DO_VTOL_TRANSITION
        //  https://mavlink.io/en/messages/common.html#MAV_CMD_DO_VTOL_TRANSITION
        public Std.MHeader header;
        //  MAV_VTOL_STATE
        public const byte STATE_MC = 3;
        public const byte STATE_FW = 4;
        public byte state;
        //  See enum MAV_VTOL_STATE.

        public MCommandVtolTransitionRequest()
        {
            this.header = new Std.MHeader();
            this.state = 0;
        }

        public MCommandVtolTransitionRequest(Std.MHeader header, byte state)
        {
            this.header = header;
            this.state = state;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.Add(new[]{this.state});

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            this.state = data[offset];;
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MCommandVtolTransitionRequest: " +
            "\nheader: " + header.ToString() +
            "\nstate: " + state.ToString();
        }
    }
}
