//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MCommandHomeRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/CommandHome";

        //  request set new home position
        public bool current_gps;
        public float yaw;
        public float latitude;
        public float longitude;
        public float altitude;

        public MCommandHomeRequest()
        {
            this.current_gps = false;
            this.yaw = 0.0f;
            this.latitude = 0.0f;
            this.longitude = 0.0f;
            this.altitude = 0.0f;
        }

        public MCommandHomeRequest(bool current_gps, float yaw, float latitude, float longitude, float altitude)
        {
            this.current_gps = current_gps;
            this.yaw = yaw;
            this.latitude = latitude;
            this.longitude = longitude;
            this.altitude = altitude;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.current_gps));
            listOfSerializations.Add(BitConverter.GetBytes(this.yaw));
            listOfSerializations.Add(BitConverter.GetBytes(this.latitude));
            listOfSerializations.Add(BitConverter.GetBytes(this.longitude));
            listOfSerializations.Add(BitConverter.GetBytes(this.altitude));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.current_gps = BitConverter.ToBoolean(data, offset);
            offset += 1;
            this.yaw = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.latitude = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.longitude = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.altitude = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MCommandHomeRequest: " +
            "\ncurrent_gps: " + current_gps.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString() +
            "\naltitude: " + altitude.ToString();
        }
    }
}
