//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MCommandTriggerIntervalRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/CommandTriggerInterval";

        //  Type for controlling camera trigger interval and integration time
        public float cycle_time;
        //  Trigger cycle_time (interval between to triggers) - set to 0 to ignore command
        public float integration_time;
        //  Camera shutter integration_time - set to 0 to ignore command

        public MCommandTriggerIntervalRequest()
        {
            this.cycle_time = 0.0f;
            this.integration_time = 0.0f;
        }

        public MCommandTriggerIntervalRequest(float cycle_time, float integration_time)
        {
            this.cycle_time = cycle_time;
            this.integration_time = integration_time;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.cycle_time));
            listOfSerializations.Add(BitConverter.GetBytes(this.integration_time));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.cycle_time = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.integration_time = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MCommandTriggerIntervalRequest: " +
            "\ncycle_time: " + cycle_time.ToString() +
            "\nintegration_time: " + integration_time.ToString();
        }
    }
}
