//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MCommandBoolRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/CommandBool";

        //  Common type for switch commands
        public bool value;

        public MCommandBoolRequest()
        {
            this.value = false;
        }

        public MCommandBoolRequest(bool value)
        {
            this.value = value;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.value));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.value = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MCommandBoolRequest: " +
            "\nvalue: " + value.ToString();
        }
    }
}
