//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MCommandTriggerControlRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/CommandTriggerControl";

        //  Type for controlling onboard camera triggering system
        public bool trigger_enable;
        //  Trigger enable/disable
        public bool sequence_reset;
        //  Reset the trigger sequence
        public bool trigger_pause;
        //  Pause triggering, but without switching the camera off or retracting it.

        public MCommandTriggerControlRequest()
        {
            this.trigger_enable = false;
            this.sequence_reset = false;
            this.trigger_pause = false;
        }

        public MCommandTriggerControlRequest(bool trigger_enable, bool sequence_reset, bool trigger_pause)
        {
            this.trigger_enable = trigger_enable;
            this.sequence_reset = sequence_reset;
            this.trigger_pause = trigger_pause;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.trigger_enable));
            listOfSerializations.Add(BitConverter.GetBytes(this.sequence_reset));
            listOfSerializations.Add(BitConverter.GetBytes(this.trigger_pause));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.trigger_enable = BitConverter.ToBoolean(data, offset);
            offset += 1;
            this.sequence_reset = BitConverter.ToBoolean(data, offset);
            offset += 1;
            this.trigger_pause = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MCommandTriggerControlRequest: " +
            "\ntrigger_enable: " + trigger_enable.ToString() +
            "\nsequence_reset: " + sequence_reset.ToString() +
            "\ntrigger_pause: " + trigger_pause.ToString();
        }
    }
}
