//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MCommandIntResponse : Message
    {
        public const string RosMessageName = "mavros_msgs/CommandInt";

        public bool success;
        //  seems that this message don't produce andy COMMAND_ACK messages
        //  so no result field

        public MCommandIntResponse()
        {
            this.success = false;
        }

        public MCommandIntResponse(bool success)
        {
            this.success = success;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.success));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.success = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MCommandIntResponse: " +
            "\nsuccess: " + success.ToString();
        }
    }
}
