//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MFileTruncateRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/FileTruncate";

        //  FTP::Truncate
        // 
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public string file_path;
        public ulong length;

        public MFileTruncateRequest()
        {
            this.file_path = "";
            this.length = 0;
        }

        public MFileTruncateRequest(string file_path, ulong length)
        {
            this.file_path = file_path;
            this.length = length;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.file_path));
            listOfSerializations.Add(BitConverter.GetBytes(this.length));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var file_pathStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.file_path = DeserializeString(data, offset, file_pathStringBytesLength);
            offset += file_pathStringBytesLength;
            this.length = BitConverter.ToUInt64(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MFileTruncateRequest: " +
            "\nfile_path: " + file_path.ToString() +
            "\nlength: " + length.ToString();
        }
    }
}
