//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MFileCloseRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/FileClose";

        //  FTP::Close
        // 
        //  Call FTP::Open first.
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public string file_path;

        public MFileCloseRequest()
        {
            this.file_path = "";
        }

        public MFileCloseRequest(string file_path)
        {
            this.file_path = file_path;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.file_path));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var file_pathStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.file_path = DeserializeString(data, offset, file_pathStringBytesLength);
            offset += file_pathStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MFileCloseRequest: " +
            "\nfile_path: " + file_path.ToString();
        }
    }
}
