//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MFileMakeDirRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/FileMakeDir";

        //  FTP::MakeDir
        // 
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public string dir_path;

        public MFileMakeDirRequest()
        {
            this.dir_path = "";
        }

        public MFileMakeDirRequest(string dir_path)
        {
            this.dir_path = dir_path;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.dir_path));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var dir_pathStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.dir_path = DeserializeString(data, offset, dir_pathStringBytesLength);
            offset += dir_pathStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MFileMakeDirRequest: " +
            "\ndir_path: " + dir_path.ToString();
        }
    }
}
