//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MFileOpenRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/FileOpen";

        //  FTP::Open
        // 
        //  :file_path:	used as session id in read/write/close services
        //  :size:	file size returned for MODE_READ
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public const byte MODE_READ = 0; //  open for read
        public const byte MODE_WRITE = 1; //  open for write
        public const byte MODE_CREATE = 2; //  do creat()
        public string file_path;
        public byte mode;

        public MFileOpenRequest()
        {
            this.file_path = "";
            this.mode = 0;
        }

        public MFileOpenRequest(string file_path, byte mode)
        {
            this.file_path = file_path;
            this.mode = mode;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.file_path));
            listOfSerializations.Add(new[]{this.mode});

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var file_pathStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.file_path = DeserializeString(data, offset, file_pathStringBytesLength);
            offset += file_pathStringBytesLength;
            this.mode = data[offset];;
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MFileOpenRequest: " +
            "\nfile_path: " + file_path.ToString() +
            "\nmode: " + mode.ToString();
        }
    }
}
