//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MFileReadRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/FileRead";

        //  FTP::Read
        // 
        //  Call FTP::Open first.
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public string file_path;
        public ulong offset;
        public ulong size;

        public MFileReadRequest()
        {
            this.file_path = "";
            this.offset = 0;
            this.size = 0;
        }

        public MFileReadRequest(string file_path, ulong offset, ulong size)
        {
            this.file_path = file_path;
            this.offset = offset;
            this.size = size;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.file_path));
            listOfSerializations.Add(BitConverter.GetBytes(this.offset));
            listOfSerializations.Add(BitConverter.GetBytes(this.size));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var file_pathStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.file_path = DeserializeString(data, offset, file_pathStringBytesLength);
            offset += file_pathStringBytesLength;
            this.offset = BitConverter.ToUInt64(data, offset);
            offset += 8;
            this.size = BitConverter.ToUInt64(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MFileReadRequest: " +
            "\nfile_path: " + file_path.ToString() +
            "\noffset: " + offset.ToString() +
            "\nsize: " + size.ToString();
        }
    }
}
