//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MLogRequestListRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/LogRequestList";

        //  Request a list of available logs
        // 
        //   :start: - first log id (0 for first available)
        //   :end: - last log id (0xffff for last available)
        public ushort start;
        public ushort end;

        public MLogRequestListRequest()
        {
            this.start = 0;
            this.end = 0;
        }

        public MLogRequestListRequest(ushort start, ushort end)
        {
            this.start = start;
            this.end = end;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.start));
            listOfSerializations.Add(BitConverter.GetBytes(this.end));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.start = BitConverter.ToUInt16(data, offset);
            offset += 2;
            this.end = BitConverter.ToUInt16(data, offset);
            offset += 2;

            return offset;
        }

        public override string ToString()
        {
            return "MLogRequestListRequest: " +
            "\nstart: " + start.ToString() +
            "\nend: " + end.ToString();
        }
    }
}
