//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MParamSetRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/ParamSet";

        //  Request set parameter value
        public string param_id;
        public MParamValue value;

        public MParamSetRequest()
        {
            this.param_id = "";
            this.value = new MParamValue();
        }

        public MParamSetRequest(string param_id, MParamValue value)
        {
            this.param_id = param_id;
            this.value = value;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.param_id));
            listOfSerializations.AddRange(value.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var param_idStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.param_id = DeserializeString(data, offset, param_idStringBytesLength);
            offset += param_idStringBytesLength;
            offset = this.value.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MParamSetRequest: " +
            "\nparam_id: " + param_id.ToString() +
            "\nvalue: " + value.ToString();
        }
    }
}
