//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MParamGetRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/ParamGet";

        //  Request parameter from attached device
        public string param_id;

        public MParamGetRequest()
        {
            this.param_id = "";
        }

        public MParamGetRequest(string param_id)
        {
            this.param_id = param_id;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.param_id));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var param_idStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.param_id = DeserializeString(data, offset, param_idStringBytesLength);
            offset += param_idStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MParamGetRequest: " +
            "\nparam_id: " + param_id.ToString();
        }
    }
}
