//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MParamGetResponse : Message
    {
        public const string RosMessageName = "mavros_msgs/ParamGet";

        public bool success;
        public MParamValue value;

        public MParamGetResponse()
        {
            this.success = false;
            this.value = new MParamValue();
        }

        public MParamGetResponse(bool success, MParamValue value)
        {
            this.success = success;
            this.value = value;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.success));
            listOfSerializations.AddRange(value.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.success = BitConverter.ToBoolean(data, offset);
            offset += 1;
            offset = this.value.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MParamGetResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nvalue: " + value.ToString();
        }
    }
}
