//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MParamPullResponse : Message
    {
        public const string RosMessageName = "mavros_msgs/ParamPull";

        public bool success;
        public uint param_received;

        public MParamPullResponse()
        {
            this.success = false;
            this.param_received = 0;
        }

        public MParamPullResponse(bool success, uint param_received)
        {
            this.success = success;
            this.param_received = param_received;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.success));
            listOfSerializations.Add(BitConverter.GetBytes(this.param_received));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.success = BitConverter.ToBoolean(data, offset);
            offset += 1;
            this.param_received = BitConverter.ToUInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MParamPullResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nparam_received: " + param_received.ToString();
        }
    }
}
