//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MSetModeResponse : Message
    {
        public const string RosMessageName = "mavros_msgs/SetMode";

        public bool mode_sent;
        //  Mode known/parsed correctly and SET_MODE are sent

        public MSetModeResponse()
        {
            this.mode_sent = false;
        }

        public MSetModeResponse(bool mode_sent)
        {
            this.mode_sent = mode_sent;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.mode_sent));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.mode_sent = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MSetModeResponse: " +
            "\nmode_sent: " + mode_sent.ToString();
        }
    }
}
