//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MVehicleInfoGetRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/VehicleInfoGet";

        //  Request the Vehicle Info
        //  use this to request the current target sysid / compid defined in mavros
        //  set get_all = True to request all available vehicles
        public const byte GET_MY_SYSID = 0;
        public const byte GET_MY_COMPID = 0;
        public byte sysid;
        public byte compid;
        public bool get_all;

        public MVehicleInfoGetRequest()
        {
            this.sysid = 0;
            this.compid = 0;
            this.get_all = false;
        }

        public MVehicleInfoGetRequest(byte sysid, byte compid, bool get_all)
        {
            this.sysid = sysid;
            this.compid = compid;
            this.get_all = get_all;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(new[]{this.sysid});
            listOfSerializations.Add(new[]{this.compid});
            listOfSerializations.Add(BitConverter.GetBytes(this.get_all));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.sysid = data[offset];;
            offset += 1;
            this.compid = data[offset];;
            offset += 1;
            this.get_all = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MVehicleInfoGetRequest: " +
            "\nsysid: " + sysid.ToString() +
            "\ncompid: " + compid.ToString() +
            "\nget_all: " + get_all.ToString();
        }
    }
}
