//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MVehicleInfoGetResponse : Message
    {
        public const string RosMessageName = "mavros_msgs/VehicleInfoGet";

        public bool success;
        public MVehicleInfo[] vehicles;

        public MVehicleInfoGetResponse()
        {
            this.success = false;
            this.vehicles = new MVehicleInfo[0];
        }

        public MVehicleInfoGetResponse(bool success, MVehicleInfo[] vehicles)
        {
            this.success = success;
            this.vehicles = vehicles;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.success));
            
            listOfSerializations.Add(BitConverter.GetBytes(vehicles.Length));
            foreach(var entry in vehicles)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.success = BitConverter.ToBoolean(data, offset);
            offset += 1;
            
            var vehiclesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.vehicles= new MVehicleInfo[vehiclesArrayLength];
            for(var i = 0; i < vehiclesArrayLength; i++)
            {
                this.vehicles[i] = new MVehicleInfo();
                offset = this.vehicles[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MVehicleInfoGetResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nvehicles: " + System.String.Join(", ", vehicles.ToList());
        }
    }
}
