//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MWaypointPullResponse : Message
    {
        public const string RosMessageName = "mavros_msgs/WaypointPull";

        public bool success;
        public uint wp_received;

        public MWaypointPullResponse()
        {
            this.success = false;
            this.wp_received = 0;
        }

        public MWaypointPullResponse(bool success, uint wp_received)
        {
            this.success = success;
            this.wp_received = wp_received;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.success));
            listOfSerializations.Add(BitConverter.GetBytes(this.wp_received));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.success = BitConverter.ToBoolean(data, offset);
            offset += 1;
            this.wp_received = BitConverter.ToUInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MWaypointPullResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nwp_received: " + wp_received.ToString();
        }
    }
}
