//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MWaypointSetCurrentRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/WaypointSetCurrent";

        //  Request set current waypoint
        // 
        //  wp_seq - index in waypoint array
        public ushort wp_seq;

        public MWaypointSetCurrentRequest()
        {
            this.wp_seq = 0;
        }

        public MWaypointSetCurrentRequest(ushort wp_seq)
        {
            this.wp_seq = wp_seq;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.wp_seq));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.wp_seq = BitConverter.ToUInt16(data, offset);
            offset += 2;

            return offset;
        }

        public override string ToString()
        {
            return "MWaypointSetCurrentRequest: " +
            "\nwp_seq: " + wp_seq.ToString();
        }
    }
}
