//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MWaypointPushRequest : Message
    {
        public const string RosMessageName = "mavros_msgs/WaypointPush";

        //  Send waypoints to device
        // 
        //   :start_index: will define a partial waypoint update. Set to 0 for full update
        // 
        //  Returns success status and transfered count
        public ushort start_index;
        public MWaypoint[] waypoints;

        public MWaypointPushRequest()
        {
            this.start_index = 0;
            this.waypoints = new MWaypoint[0];
        }

        public MWaypointPushRequest(ushort start_index, MWaypoint[] waypoints)
        {
            this.start_index = start_index;
            this.waypoints = waypoints;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.start_index));
            
            listOfSerializations.Add(BitConverter.GetBytes(waypoints.Length));
            foreach(var entry in waypoints)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.start_index = BitConverter.ToUInt16(data, offset);
            offset += 2;
            
            var waypointsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.waypoints= new MWaypoint[waypointsArrayLength];
            for(var i = 0; i < waypointsArrayLength; i++)
            {
                this.waypoints[i] = new MWaypoint();
                offset = this.waypoints[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MWaypointPushRequest: " +
            "\nstart_index: " + start_index.ToString() +
            "\nwaypoints: " + System.String.Join(", ", waypoints.ToList());
        }
    }
}
