//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MWaypointPushResponse : Message
    {
        public const string RosMessageName = "mavros_msgs/WaypointPush";

        public bool success;
        public uint wp_transfered;

        public MWaypointPushResponse()
        {
            this.success = false;
            this.wp_transfered = 0;
        }

        public MWaypointPushResponse(bool success, uint wp_transfered)
        {
            this.success = success;
            this.wp_transfered = wp_transfered;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.success));
            listOfSerializations.Add(BitConverter.GetBytes(this.wp_transfered));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.success = BitConverter.ToBoolean(data, offset);
            offset += 1;
            this.wp_transfered = BitConverter.ToUInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MWaypointPushResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nwp_transfered: " + wp_transfered.ToString();
        }
    }
}
