//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    public class MGetRoutePlanRequest : Message
    {
        public const string RosMessageName = "geographic_msgs/GetRoutePlan";

        //  Get a plan to traverse a route network from start to goal.
        // 
        //  Similar to nav_msgs/GetPlan, but constrained to use the route network.
        public Uuid.MUniqueID network;
        //  route network to use
        public Uuid.MUniqueID start;
        //  starting way point
        public Uuid.MUniqueID goal;
        //  goal way point

        public MGetRoutePlanRequest()
        {
            this.network = new Uuid.MUniqueID();
            this.start = new Uuid.MUniqueID();
            this.goal = new Uuid.MUniqueID();
        }

        public MGetRoutePlanRequest(Uuid.MUniqueID network, Uuid.MUniqueID start, Uuid.MUniqueID goal)
        {
            this.network = network;
            this.start = start;
            this.goal = goal;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(network.SerializationStatements());
            listOfSerializations.AddRange(start.SerializationStatements());
            listOfSerializations.AddRange(goal.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.network.Deserialize(data, offset);
            offset = this.start.Deserialize(data, offset);
            offset = this.goal.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MGetRoutePlanRequest: " +
            "\nnetwork: " + network.ToString() +
            "\nstart: " + start.ToString() +
            "\ngoal: " + goal.ToString();
        }
    }
}
