//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    public class MUpdateGeographicMapRequest : Message
    {
        public const string RosMessageName = "geographic_msgs/UpdateGeographicMap";

        //  This service updates a geographic map.
        //  Changes to geographic map.
        public MGeographicMapChanges updates;

        public MUpdateGeographicMapRequest()
        {
            this.updates = new MGeographicMapChanges();
        }

        public MUpdateGeographicMapRequest(MGeographicMapChanges updates)
        {
            this.updates = updates;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(updates.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.updates.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MUpdateGeographicMapRequest: " +
            "\nupdates: " + updates.ToString();
        }
    }
}
