//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class BatteryStatusMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/BatteryStatus";
        public override string RosMessageName => k_RosMessageName;

        //  Represent battery status from SYSTEM_STATUS
        // 
        //  To be replaced when sensor_msgs/BatteryState PR will be merged
        //  https://github.com/ros/common_msgs/pull/74
        public Std.HeaderMsg header;
        public float voltage;
        //  [V]
        public float current;
        //  [A]
        public float remaining;
        //  0..1

        public BatteryStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.voltage = 0.0f;
            this.current = 0.0f;
            this.remaining = 0.0f;
        }

        public BatteryStatusMsg(Std.HeaderMsg header, float voltage, float current, float remaining)
        {
            this.header = header;
            this.voltage = voltage;
            this.current = current;
            this.remaining = remaining;
        }

        public static BatteryStatusMsg Deserialize(MessageDeserializer deserializer) => new BatteryStatusMsg(deserializer);

        private BatteryStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.voltage);
            deserializer.Read(out this.current);
            deserializer.Read(out this.remaining);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.voltage);
            serializer.Write(this.current);
            serializer.Write(this.remaining);
        }

        public override string ToString()
        {
            return "BatteryStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nvoltage: " + voltage.ToString() +
            "\ncurrent: " + current.ToString() +
            "\nremaining: " + remaining.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
