//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CamIMUStampMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CamIMUStamp";
        public override string RosMessageName => k_RosMessageName;

        //  IMU-Camera synchronisation data
        public TimeMsg frame_stamp;
        //  Timestamp when the camera was triggered
        public int frame_seq_id;
        //  Sequence number of the image frame

        public CamIMUStampMsg()
        {
            this.frame_stamp = new TimeMsg();
            this.frame_seq_id = 0;
        }

        public CamIMUStampMsg(TimeMsg frame_stamp, int frame_seq_id)
        {
            this.frame_stamp = frame_stamp;
            this.frame_seq_id = frame_seq_id;
        }

        public static CamIMUStampMsg Deserialize(MessageDeserializer deserializer) => new CamIMUStampMsg(deserializer);

        private CamIMUStampMsg(MessageDeserializer deserializer)
        {
            this.frame_stamp = TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.frame_seq_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frame_stamp);
            serializer.Write(this.frame_seq_id);
        }

        public override string ToString()
        {
            return "CamIMUStampMsg: " +
            "\nframe_stamp: " + frame_stamp.ToString() +
            "\nframe_seq_id: " + frame_seq_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
