//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CompanionProcessStatusMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CompanionProcessStatus";
        public override string RosMessageName => k_RosMessageName;

        //  Mavros message: COMPANIONPROCESSSTATUS
        public Std.HeaderMsg header;
        public byte state;
        //  See enum COMPANION_PROCESS_STATE
        public byte component;
        //  See enum MAV_COMPONENT
        public const byte MAV_STATE_UNINIT = 0;
        public const byte MAV_STATE_BOOT = 1;
        public const byte MAV_STATE_CALIBRATING = 2;
        public const byte MAV_STATE_STANDBY = 3;
        public const byte MAV_STATE_ACTIVE = 4;
        public const byte MAV_STATE_CRITICAL = 5;
        public const byte MAV_STATE_EMERGENCY = 6;
        public const byte MAV_STATE_POWEROFF = 7;
        public const byte MAV_STATE_FLIGHT_TERMINATION = 8;
        public const byte MAV_COMP_ID_OBSTACLE_AVOIDANCE = 196;
        public const byte MAV_COMP_ID_VISUAL_INERTIAL_ODOMETRY = 197;

        public CompanionProcessStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.state = 0;
            this.component = 0;
        }

        public CompanionProcessStatusMsg(Std.HeaderMsg header, byte state, byte component)
        {
            this.header = header;
            this.state = state;
            this.component = component;
        }

        public static CompanionProcessStatusMsg Deserialize(MessageDeserializer deserializer) => new CompanionProcessStatusMsg(deserializer);

        private CompanionProcessStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.state);
            deserializer.Read(out this.component);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.state);
            serializer.Write(this.component);
        }

        public override string ToString()
        {
            return "CompanionProcessStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nstate: " + state.ToString() +
            "\ncomponent: " + component.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
