//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ESCInfoMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ESCInfo";
        public override string RosMessageName => k_RosMessageName;

        //  ESCInfo.msg
        // 
        // 
        //  See mavlink message documentation here:
        //  https://mavlink.io/en/messages/common.html#ESC_INFO
        public Std.HeaderMsg header;
        public ushort counter;
        public byte count;
        public byte connection_type;
        public byte info;
        public ESCInfoItemMsg[] esc_info;

        public ESCInfoMsg()
        {
            this.header = new Std.HeaderMsg();
            this.counter = 0;
            this.count = 0;
            this.connection_type = 0;
            this.info = 0;
            this.esc_info = new ESCInfoItemMsg[0];
        }

        public ESCInfoMsg(Std.HeaderMsg header, ushort counter, byte count, byte connection_type, byte info, ESCInfoItemMsg[] esc_info)
        {
            this.header = header;
            this.counter = counter;
            this.count = count;
            this.connection_type = connection_type;
            this.info = info;
            this.esc_info = esc_info;
        }

        public static ESCInfoMsg Deserialize(MessageDeserializer deserializer) => new ESCInfoMsg(deserializer);

        private ESCInfoMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.counter);
            deserializer.Read(out this.count);
            deserializer.Read(out this.connection_type);
            deserializer.Read(out this.info);
            deserializer.Read(out this.esc_info, ESCInfoItemMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.counter);
            serializer.Write(this.count);
            serializer.Write(this.connection_type);
            serializer.Write(this.info);
            serializer.WriteLength(this.esc_info);
            serializer.Write(this.esc_info);
        }

        public override string ToString()
        {
            return "ESCInfoMsg: " +
            "\nheader: " + header.ToString() +
            "\ncounter: " + counter.ToString() +
            "\ncount: " + count.ToString() +
            "\nconnection_type: " + connection_type.ToString() +
            "\ninfo: " + info.ToString() +
            "\nesc_info: " + System.String.Join(", ", esc_info.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
