//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ESCStatusItemMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ESCStatusItem";
        public override string RosMessageName => k_RosMessageName;

        //  ESCStatusItem.msg
        // 
        // 
        //  See mavlink message documentation here:
        //  https://mavlink.io/en/messages/common.html#ESC_STATUS
        public Std.HeaderMsg header;
        public int rpm;
        public float voltage;
        public float current;

        public ESCStatusItemMsg()
        {
            this.header = new Std.HeaderMsg();
            this.rpm = 0;
            this.voltage = 0.0f;
            this.current = 0.0f;
        }

        public ESCStatusItemMsg(Std.HeaderMsg header, int rpm, float voltage, float current)
        {
            this.header = header;
            this.rpm = rpm;
            this.voltage = voltage;
            this.current = current;
        }

        public static ESCStatusItemMsg Deserialize(MessageDeserializer deserializer) => new ESCStatusItemMsg(deserializer);

        private ESCStatusItemMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.rpm);
            deserializer.Read(out this.voltage);
            deserializer.Read(out this.current);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.rpm);
            serializer.Write(this.voltage);
            serializer.Write(this.current);
        }

        public override string ToString()
        {
            return "ESCStatusItemMsg: " +
            "\nheader: " + header.ToString() +
            "\nrpm: " + rpm.ToString() +
            "\nvoltage: " + voltage.ToString() +
            "\ncurrent: " + current.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
