//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class EstimatorStatusMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/EstimatorStatus";
        public override string RosMessageName => k_RosMessageName;

        //  Current autopilot estimator state
        // 
        //  https://mavlink.io/en/messages/common.html#ESTIMATOR_STATUS_FLAGS
        public Std.HeaderMsg header;
        public bool attitude_status_flag;
        public bool velocity_horiz_status_flag;
        public bool velocity_vert_status_flag;
        public bool pos_horiz_rel_status_flag;
        public bool pos_horiz_abs_status_flag;
        public bool pos_vert_abs_status_flag;
        public bool pos_vert_agl_status_flag;
        public bool const_pos_mode_status_flag;
        public bool pred_pos_horiz_rel_status_flag;
        public bool pred_pos_horiz_abs_status_flag;
        public bool gps_glitch_status_flag;
        public bool accel_error_status_flag;

        public EstimatorStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.attitude_status_flag = false;
            this.velocity_horiz_status_flag = false;
            this.velocity_vert_status_flag = false;
            this.pos_horiz_rel_status_flag = false;
            this.pos_horiz_abs_status_flag = false;
            this.pos_vert_abs_status_flag = false;
            this.pos_vert_agl_status_flag = false;
            this.const_pos_mode_status_flag = false;
            this.pred_pos_horiz_rel_status_flag = false;
            this.pred_pos_horiz_abs_status_flag = false;
            this.gps_glitch_status_flag = false;
            this.accel_error_status_flag = false;
        }

        public EstimatorStatusMsg(Std.HeaderMsg header, bool attitude_status_flag, bool velocity_horiz_status_flag, bool velocity_vert_status_flag, bool pos_horiz_rel_status_flag, bool pos_horiz_abs_status_flag, bool pos_vert_abs_status_flag, bool pos_vert_agl_status_flag, bool const_pos_mode_status_flag, bool pred_pos_horiz_rel_status_flag, bool pred_pos_horiz_abs_status_flag, bool gps_glitch_status_flag, bool accel_error_status_flag)
        {
            this.header = header;
            this.attitude_status_flag = attitude_status_flag;
            this.velocity_horiz_status_flag = velocity_horiz_status_flag;
            this.velocity_vert_status_flag = velocity_vert_status_flag;
            this.pos_horiz_rel_status_flag = pos_horiz_rel_status_flag;
            this.pos_horiz_abs_status_flag = pos_horiz_abs_status_flag;
            this.pos_vert_abs_status_flag = pos_vert_abs_status_flag;
            this.pos_vert_agl_status_flag = pos_vert_agl_status_flag;
            this.const_pos_mode_status_flag = const_pos_mode_status_flag;
            this.pred_pos_horiz_rel_status_flag = pred_pos_horiz_rel_status_flag;
            this.pred_pos_horiz_abs_status_flag = pred_pos_horiz_abs_status_flag;
            this.gps_glitch_status_flag = gps_glitch_status_flag;
            this.accel_error_status_flag = accel_error_status_flag;
        }

        public static EstimatorStatusMsg Deserialize(MessageDeserializer deserializer) => new EstimatorStatusMsg(deserializer);

        private EstimatorStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.attitude_status_flag);
            deserializer.Read(out this.velocity_horiz_status_flag);
            deserializer.Read(out this.velocity_vert_status_flag);
            deserializer.Read(out this.pos_horiz_rel_status_flag);
            deserializer.Read(out this.pos_horiz_abs_status_flag);
            deserializer.Read(out this.pos_vert_abs_status_flag);
            deserializer.Read(out this.pos_vert_agl_status_flag);
            deserializer.Read(out this.const_pos_mode_status_flag);
            deserializer.Read(out this.pred_pos_horiz_rel_status_flag);
            deserializer.Read(out this.pred_pos_horiz_abs_status_flag);
            deserializer.Read(out this.gps_glitch_status_flag);
            deserializer.Read(out this.accel_error_status_flag);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.attitude_status_flag);
            serializer.Write(this.velocity_horiz_status_flag);
            serializer.Write(this.velocity_vert_status_flag);
            serializer.Write(this.pos_horiz_rel_status_flag);
            serializer.Write(this.pos_horiz_abs_status_flag);
            serializer.Write(this.pos_vert_abs_status_flag);
            serializer.Write(this.pos_vert_agl_status_flag);
            serializer.Write(this.const_pos_mode_status_flag);
            serializer.Write(this.pred_pos_horiz_rel_status_flag);
            serializer.Write(this.pred_pos_horiz_abs_status_flag);
            serializer.Write(this.gps_glitch_status_flag);
            serializer.Write(this.accel_error_status_flag);
        }

        public override string ToString()
        {
            return "EstimatorStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nattitude_status_flag: " + attitude_status_flag.ToString() +
            "\nvelocity_horiz_status_flag: " + velocity_horiz_status_flag.ToString() +
            "\nvelocity_vert_status_flag: " + velocity_vert_status_flag.ToString() +
            "\npos_horiz_rel_status_flag: " + pos_horiz_rel_status_flag.ToString() +
            "\npos_horiz_abs_status_flag: " + pos_horiz_abs_status_flag.ToString() +
            "\npos_vert_abs_status_flag: " + pos_vert_abs_status_flag.ToString() +
            "\npos_vert_agl_status_flag: " + pos_vert_agl_status_flag.ToString() +
            "\nconst_pos_mode_status_flag: " + const_pos_mode_status_flag.ToString() +
            "\npred_pos_horiz_rel_status_flag: " + pred_pos_horiz_rel_status_flag.ToString() +
            "\npred_pos_horiz_abs_status_flag: " + pred_pos_horiz_abs_status_flag.ToString() +
            "\ngps_glitch_status_flag: " + gps_glitch_status_flag.ToString() +
            "\naccel_error_status_flag: " + accel_error_status_flag.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
