//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ExtendedStateMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ExtendedState";
        public override string RosMessageName => k_RosMessageName;

        //  Extended autopilot state
        // 
        //  https://mavlink.io/en/messages/common.html#EXTENDED_SYS_STATE
        public const byte VTOL_STATE_UNDEFINED = 0;
        public const byte VTOL_STATE_TRANSITION_TO_FW = 1;
        public const byte VTOL_STATE_TRANSITION_TO_MC = 2;
        public const byte VTOL_STATE_MC = 3;
        public const byte VTOL_STATE_FW = 4;
        public const byte LANDED_STATE_UNDEFINED = 0;
        public const byte LANDED_STATE_ON_GROUND = 1;
        public const byte LANDED_STATE_IN_AIR = 2;
        public const byte LANDED_STATE_TAKEOFF = 3;
        public const byte LANDED_STATE_LANDING = 4;
        public Std.HeaderMsg header;
        public byte vtol_state;
        public byte landed_state;

        public ExtendedStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.vtol_state = 0;
            this.landed_state = 0;
        }

        public ExtendedStateMsg(Std.HeaderMsg header, byte vtol_state, byte landed_state)
        {
            this.header = header;
            this.vtol_state = vtol_state;
            this.landed_state = landed_state;
        }

        public static ExtendedStateMsg Deserialize(MessageDeserializer deserializer) => new ExtendedStateMsg(deserializer);

        private ExtendedStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.vtol_state);
            deserializer.Read(out this.landed_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.vtol_state);
            serializer.Write(this.landed_state);
        }

        public override string ToString()
        {
            return "ExtendedStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nvtol_state: " + vtol_state.ToString() +
            "\nlanded_state: " + landed_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
