//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class LogDataMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/LogData";
        public override string RosMessageName => k_RosMessageName;

        //  Reply to LogRequestData, - a chunk of a log
        // 
        //   :id: - log id
        //   :offset: - offset into the log
        //   :data: - chunk of data (if zero-sized, then there are no more chunks)
        public Std.HeaderMsg header;
        public ushort id;
        public uint offset;
        public byte[] data;

        public LogDataMsg()
        {
            this.header = new Std.HeaderMsg();
            this.id = 0;
            this.offset = 0;
            this.data = new byte[0];
        }

        public LogDataMsg(Std.HeaderMsg header, ushort id, uint offset, byte[] data)
        {
            this.header = header;
            this.id = id;
            this.offset = offset;
            this.data = data;
        }

        public static LogDataMsg Deserialize(MessageDeserializer deserializer) => new LogDataMsg(deserializer);

        private LogDataMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.id);
            deserializer.Read(out this.offset);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.id);
            serializer.Write(this.offset);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "LogDataMsg: " +
            "\nheader: " + header.ToString() +
            "\nid: " + id.ToString() +
            "\noffset: " + offset.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
