//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Mavros
{
    public class MCamIMUStamp : Message
    {
        public const string RosMessageName = "mavros_msgs/CamIMUStamp";

        //  IMU-Camera synchronisation data
        public MTime frame_stamp;
        //  Timestamp when the camera was triggered
        public int frame_seq_id;
        //  Sequence number of the image frame

        public MCamIMUStamp()
        {
            this.frame_stamp = new MTime();
            this.frame_seq_id = 0;
        }

        public MCamIMUStamp(MTime frame_stamp, int frame_seq_id)
        {
            this.frame_stamp = frame_stamp;
            this.frame_seq_id = frame_seq_id;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(frame_stamp.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.frame_seq_id));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.frame_stamp.Deserialize(data, offset);
            this.frame_seq_id = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MCamIMUStamp: " +
            "\nframe_stamp: " + frame_stamp.ToString() +
            "\nframe_seq_id: " + frame_seq_id.ToString();
        }
    }
}
