//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MESCStatusItem : Message
    {
        public const string RosMessageName = "mavros_msgs/ESCStatusItem";

        //  ESCStatusItem.msg
        // 
        // 
        //  See mavlink message documentation here:
        //  https://mavlink.io/en/messages/common.html#ESC_STATUS
        public Std.MHeader header;
        public int rpm;
        public float voltage;
        public float current;

        public MESCStatusItem()
        {
            this.header = new Std.MHeader();
            this.rpm = 0;
            this.voltage = 0.0f;
            this.current = 0.0f;
        }

        public MESCStatusItem(Std.MHeader header, int rpm, float voltage, float current)
        {
            this.header = header;
            this.rpm = rpm;
            this.voltage = voltage;
            this.current = current;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.rpm));
            listOfSerializations.Add(BitConverter.GetBytes(this.voltage));
            listOfSerializations.Add(BitConverter.GetBytes(this.current));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            this.rpm = BitConverter.ToInt32(data, offset);
            offset += 4;
            this.voltage = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.current = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MESCStatusItem: " +
            "\nheader: " + header.ToString() +
            "\nrpm: " + rpm.ToString() +
            "\nvoltage: " + voltage.ToString() +
            "\ncurrent: " + current.ToString();
        }
    }
}
