//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MFileEntry : Message
    {
        public const string RosMessageName = "mavros_msgs/FileEntry";

        //  File/Dir information
        public const byte TYPE_FILE = 0;
        public const byte TYPE_DIRECTORY = 1;
        public string name;
        public byte type;
        public ulong size;
        //  Not supported by MAVLink FTP
        // time atime
        // int32 access_flags

        public MFileEntry()
        {
            this.name = "";
            this.type = 0;
            this.size = 0;
        }

        public MFileEntry(string name, byte type, ulong size)
        {
            this.name = name;
            this.type = type;
            this.size = size;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.name));
            listOfSerializations.Add(new[]{this.type});
            listOfSerializations.Add(BitConverter.GetBytes(this.size));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.name = DeserializeString(data, offset, nameStringBytesLength);
            offset += nameStringBytesLength;
            this.type = data[offset];;
            offset += 1;
            this.size = BitConverter.ToUInt64(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MFileEntry: " +
            "\nname: " + name.ToString() +
            "\ntype: " + type.ToString() +
            "\nsize: " + size.ToString();
        }
    }
}
