//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MHilControls : Message
    {
        public const string RosMessageName = "mavros_msgs/HilControls";

        //  HilControls.msg
        // 
        //  ROS representation of MAVLink HIL_CONTROLS
        //  (deprecated, use HIL_ACTUATOR_CONTROLS instead)
        //  See mavlink message documentation here:
        //  https://mavlink.io/en/messages/common.html#HIL_CONTROLS
        public Std.MHeader header;
        public float roll_ailerons;
        public float pitch_elevator;
        public float yaw_rudder;
        public float throttle;
        public float aux1;
        public float aux2;
        public float aux3;
        public float aux4;
        public byte mode;
        public byte nav_mode;

        public MHilControls()
        {
            this.header = new Std.MHeader();
            this.roll_ailerons = 0.0f;
            this.pitch_elevator = 0.0f;
            this.yaw_rudder = 0.0f;
            this.throttle = 0.0f;
            this.aux1 = 0.0f;
            this.aux2 = 0.0f;
            this.aux3 = 0.0f;
            this.aux4 = 0.0f;
            this.mode = 0;
            this.nav_mode = 0;
        }

        public MHilControls(Std.MHeader header, float roll_ailerons, float pitch_elevator, float yaw_rudder, float throttle, float aux1, float aux2, float aux3, float aux4, byte mode, byte nav_mode)
        {
            this.header = header;
            this.roll_ailerons = roll_ailerons;
            this.pitch_elevator = pitch_elevator;
            this.yaw_rudder = yaw_rudder;
            this.throttle = throttle;
            this.aux1 = aux1;
            this.aux2 = aux2;
            this.aux3 = aux3;
            this.aux4 = aux4;
            this.mode = mode;
            this.nav_mode = nav_mode;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.roll_ailerons));
            listOfSerializations.Add(BitConverter.GetBytes(this.pitch_elevator));
            listOfSerializations.Add(BitConverter.GetBytes(this.yaw_rudder));
            listOfSerializations.Add(BitConverter.GetBytes(this.throttle));
            listOfSerializations.Add(BitConverter.GetBytes(this.aux1));
            listOfSerializations.Add(BitConverter.GetBytes(this.aux2));
            listOfSerializations.Add(BitConverter.GetBytes(this.aux3));
            listOfSerializations.Add(BitConverter.GetBytes(this.aux4));
            listOfSerializations.Add(new[]{this.mode});
            listOfSerializations.Add(new[]{this.nav_mode});

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            this.roll_ailerons = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.pitch_elevator = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.yaw_rudder = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.throttle = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.aux1 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.aux2 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.aux3 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.aux4 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.mode = data[offset];;
            offset += 1;
            this.nav_mode = data[offset];;
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MHilControls: " +
            "\nheader: " + header.ToString() +
            "\nroll_ailerons: " + roll_ailerons.ToString() +
            "\npitch_elevator: " + pitch_elevator.ToString() +
            "\nyaw_rudder: " + yaw_rudder.ToString() +
            "\nthrottle: " + throttle.ToString() +
            "\naux1: " + aux1.ToString() +
            "\naux2: " + aux2.ToString() +
            "\naux3: " + aux3.ToString() +
            "\naux4: " + aux4.ToString() +
            "\nmode: " + mode.ToString() +
            "\nnav_mode: " + nav_mode.ToString();
        }
    }
}
