//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MManualControl : Message
    {
        public const string RosMessageName = "mavros_msgs/ManualControl";

        //  Manual Control state
        public Std.MHeader header;
        public float x;
        public float y;
        public float z;
        public float r;
        public ushort buttons;

        public MManualControl()
        {
            this.header = new Std.MHeader();
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.r = 0.0f;
            this.buttons = 0;
        }

        public MManualControl(Std.MHeader header, float x, float y, float z, float r, ushort buttons)
        {
            this.header = header;
            this.x = x;
            this.y = y;
            this.z = z;
            this.r = r;
            this.buttons = buttons;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.x));
            listOfSerializations.Add(BitConverter.GetBytes(this.y));
            listOfSerializations.Add(BitConverter.GetBytes(this.z));
            listOfSerializations.Add(BitConverter.GetBytes(this.r));
            listOfSerializations.Add(BitConverter.GetBytes(this.buttons));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            this.x = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.y = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.z = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.r = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.buttons = BitConverter.ToUInt16(data, offset);
            offset += 2;

            return offset;
        }

        public override string ToString()
        {
            return "MManualControl: " +
            "\nheader: " + header.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nr: " + r.ToString() +
            "\nbuttons: " + buttons.ToString();
        }
    }
}
