//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MParamValue : Message
    {
        public const string RosMessageName = "mavros_msgs/ParamValue";

        //  Parameter value storage type.
        // 
        //  Integer and float fields:
        // 
        //  if integer != 0: it is integer value
        //  else if real != 0.0: it is float value
        //  else: it is zero.
        public long integer;
        public double real;

        public MParamValue()
        {
            this.integer = 0;
            this.real = 0.0;
        }

        public MParamValue(long integer, double real)
        {
            this.integer = integer;
            this.real = real;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.integer));
            listOfSerializations.Add(BitConverter.GetBytes(this.real));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.integer = BitConverter.ToInt64(data, offset);
            offset += 8;
            this.real = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MParamValue: " +
            "\ninteger: " + integer.ToString() +
            "\nreal: " + real.ToString();
        }
    }
}
