//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MPlayTuneV2 : Message
    {
        public const string RosMessageName = "mavros_msgs/PlayTuneV2";

        //  Play tune V2
        // 
        //  https://mavlink.io/en/messages/common.html#PLAY_TUNE_V2
        // # TUNE_FORMAT enum
        public const byte QBASIC1_1 = 1;
        public const byte MML_MODERN = 2;
        public byte format;
        public string tune;

        public MPlayTuneV2()
        {
            this.format = 0;
            this.tune = "";
        }

        public MPlayTuneV2(byte format, string tune)
        {
            this.format = format;
            this.tune = tune;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(new[]{this.format});
            listOfSerializations.Add(SerializeString(this.tune));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.format = data[offset];;
            offset += 1;
            var tuneStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.tune = DeserializeString(data, offset, tuneStringBytesLength);
            offset += tuneStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MPlayTuneV2: " +
            "\nformat: " + format.ToString() +
            "\ntune: " + tune.ToString();
        }
    }
}
