//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MRTCM : Message
    {
        public const string RosMessageName = "mavros_msgs/RTCM";

        //  RTCM message for the gps_rtk plugin
        //  The gps_rtk plugin will fragment the data if necessary and 
        //  forward it to the FCU via Mavlink through the available link.
        //  data should be <= 4*180, higher will be discarded.
        public Std.MHeader header;
        public byte[] data;

        public MRTCM()
        {
            this.header = new Std.MHeader();
            this.data = new byte[0];
        }

        public MRTCM(Std.MHeader header, byte[] data)
        {
            this.header = header;
            this.data = data;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            
            listOfSerializations.Add(BitConverter.GetBytes(data.Length));
            listOfSerializations.Add(this.data);

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            
            var dataArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.data= new byte[dataArrayLength];
            for(var i = 0; i < dataArrayLength; i++)
            {
                this.data[i] = data[offset];
                offset += 1;
            }

            return offset;
        }

        public override string ToString()
        {
            return "MRTCM: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }
    }
}
