//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MThrust : Message
    {
        public const string RosMessageName = "mavros_msgs/Thrust";

        //  Thrust to send to the FCU
        public Std.MHeader header;
        public float thrust;

        public MThrust()
        {
            this.header = new Std.MHeader();
            this.thrust = 0.0f;
        }

        public MThrust(Std.MHeader header, float thrust)
        {
            this.header = header;
            this.thrust = thrust;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.thrust));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            this.thrust = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MThrust: " +
            "\nheader: " + header.ToString() +
            "\nthrust: " + thrust.ToString();
        }
    }
}
