//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Mavros
{
    public class MWaypointReached : Message
    {
        public const string RosMessageName = "mavros_msgs/WaypointReached";

        //  That message represent MISSION_ITEM_REACHED
        // 
        //    :wp_seq:    index number of reached waypoint
        public MHeader header;
        public ushort wp_seq;

        public MWaypointReached()
        {
            this.header = new MHeader();
            this.wp_seq = 0;
        }

        public MWaypointReached(MHeader header, ushort wp_seq)
        {
            this.header = header;
            this.wp_seq = wp_seq;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.wp_seq));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            this.wp_seq = BitConverter.ToUInt16(data, offset);
            offset += 2;

            return offset;
        }

        public override string ToString()
        {
            return "MWaypointReached: " +
            "\nheader: " + header.ToString() +
            "\nwp_seq: " + wp_seq.ToString();
        }
    }
}
