//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    public class MWheelOdomStamped : Message
    {
        public const string RosMessageName = "mavros_msgs/WheelOdomStamped";

        //  Stamped wheel odometry message
        // 
        //  For streaming timestamped data from FCU wheel encoders (RPM or WHEEL_DISTANCE).
        public Std.MHeader header;
        public double[] data;

        public MWheelOdomStamped()
        {
            this.header = new Std.MHeader();
            this.data = new double[0];
        }

        public MWheelOdomStamped(Std.MHeader header, double[] data)
        {
            this.header = header;
            this.data = data;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            
            listOfSerializations.Add(BitConverter.GetBytes(data.Length));
            foreach(var entry in data)
                listOfSerializations.Add(BitConverter.GetBytes(entry));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            
            var dataArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.data= new double[dataArrayLength];
            for(var i = 0; i < dataArrayLength; i++)
            {
                this.data[i] = BitConverter.ToDouble(data, offset);
                offset += 8;
            }

            return offset;
        }

        public override string ToString()
        {
            return "MWheelOdomStamped: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }
    }
}
