//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ParamValueMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ParamValue";
        public override string RosMessageName => k_RosMessageName;

        //  Parameter value storage type.
        // 
        //  Integer and float fields:
        // 
        //  if integer != 0: it is integer value
        //  else if real != 0.0: it is float value
        //  else: it is zero.
        public long integer;
        public double real;

        public ParamValueMsg()
        {
            this.integer = 0;
            this.real = 0.0;
        }

        public ParamValueMsg(long integer, double real)
        {
            this.integer = integer;
            this.real = real;
        }

        public static ParamValueMsg Deserialize(MessageDeserializer deserializer) => new ParamValueMsg(deserializer);

        private ParamValueMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.integer);
            deserializer.Read(out this.real);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.integer);
            serializer.Write(this.real);
        }

        public override string ToString()
        {
            return "ParamValueMsg: " +
            "\ninteger: " + integer.ToString() +
            "\nreal: " + real.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
