//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ParamMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/Param";
        public override string RosMessageName => k_RosMessageName;

        //  Parameter msg.
        public Std.HeaderMsg header;
        public string param_id;
        public ParamValueMsg value;
        public ushort param_index;
        public ushort param_count;

        public ParamMsg()
        {
            this.header = new Std.HeaderMsg();
            this.param_id = "";
            this.value = new ParamValueMsg();
            this.param_index = 0;
            this.param_count = 0;
        }

        public ParamMsg(Std.HeaderMsg header, string param_id, ParamValueMsg value, ushort param_index, ushort param_count)
        {
            this.header = header;
            this.param_id = param_id;
            this.value = value;
            this.param_index = param_index;
            this.param_count = param_count;
        }

        public static ParamMsg Deserialize(MessageDeserializer deserializer) => new ParamMsg(deserializer);

        private ParamMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.param_id);
            this.value = ParamValueMsg.Deserialize(deserializer);
            deserializer.Read(out this.param_index);
            deserializer.Read(out this.param_count);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.param_id);
            serializer.Write(this.value);
            serializer.Write(this.param_index);
            serializer.Write(this.param_count);
        }

        public override string ToString()
        {
            return "ParamMsg: " +
            "\nheader: " + header.ToString() +
            "\nparam_id: " + param_id.ToString() +
            "\nvalue: " + value.ToString() +
            "\nparam_index: " + param_index.ToString() +
            "\nparam_count: " + param_count.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
