//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class PlayTuneV2Msg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/PlayTuneV2";
        public override string RosMessageName => k_RosMessageName;

        //  Play tune V2
        // 
        //  https://mavlink.io/en/messages/common.html#PLAY_TUNE_V2
        // # TUNE_FORMAT enum
        public const byte QBASIC1_1 = 1;
        public const byte MML_MODERN = 2;
        public byte format;
        public string tune;

        public PlayTuneV2Msg()
        {
            this.format = 0;
            this.tune = "";
        }

        public PlayTuneV2Msg(byte format, string tune)
        {
            this.format = format;
            this.tune = tune;
        }

        public static PlayTuneV2Msg Deserialize(MessageDeserializer deserializer) => new PlayTuneV2Msg(deserializer);

        private PlayTuneV2Msg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.format);
            deserializer.Read(out this.tune);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.format);
            serializer.Write(this.tune);
        }

        public override string ToString()
        {
            return "PlayTuneV2Msg: " +
            "\nformat: " + format.ToString() +
            "\ntune: " + tune.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
