//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class RCInMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/RCIn";
        public override string RosMessageName => k_RosMessageName;

        //  RAW RC input state
        public Std.HeaderMsg header;
        public byte rssi;
        public ushort[] channels;

        public RCInMsg()
        {
            this.header = new Std.HeaderMsg();
            this.rssi = 0;
            this.channels = new ushort[0];
        }

        public RCInMsg(Std.HeaderMsg header, byte rssi, ushort[] channels)
        {
            this.header = header;
            this.rssi = rssi;
            this.channels = channels;
        }

        public static RCInMsg Deserialize(MessageDeserializer deserializer) => new RCInMsg(deserializer);

        private RCInMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.rssi);
            deserializer.Read(out this.channels, sizeof(ushort), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.rssi);
            serializer.WriteLength(this.channels);
            serializer.Write(this.channels);
        }

        public override string ToString()
        {
            return "RCInMsg: " +
            "\nheader: " + header.ToString() +
            "\nrssi: " + rssi.ToString() +
            "\nchannels: " + System.String.Join(", ", channels.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
