//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class RCOutMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/RCOut";
        public override string RosMessageName => k_RosMessageName;

        //  RAW Servo out state
        public Std.HeaderMsg header;
        public ushort[] channels;

        public RCOutMsg()
        {
            this.header = new Std.HeaderMsg();
            this.channels = new ushort[0];
        }

        public RCOutMsg(Std.HeaderMsg header, ushort[] channels)
        {
            this.header = header;
            this.channels = channels;
        }

        public static RCOutMsg Deserialize(MessageDeserializer deserializer) => new RCOutMsg(deserializer);

        private RCOutMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.channels, sizeof(ushort), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.channels);
            serializer.Write(this.channels);
        }

        public override string ToString()
        {
            return "RCOutMsg: " +
            "\nheader: " + header.ToString() +
            "\nchannels: " + System.String.Join(", ", channels.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
