//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class RTKBaselineMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/RTKBaseline";
        public override string RosMessageName => k_RosMessageName;

        //  RTKBaseline received from the FCU.
        //  Full description: https://mavlink.io/en/messages/common.html#GPS_RTK
        //  Mavlink Common, #127and #128
        public Std.HeaderMsg header;
        public uint time_last_baseline_ms;
        public byte rtk_receiver_id;
        public ushort wn;
        public uint tow;
        public byte rtk_health;
        public byte rtk_rate;
        public byte nsats;
        public byte baseline_coords_type;
        public const byte RTK_BASELINE_COORDINATE_SYSTEM_ECEF = 0; //  Earth-centered, earth-fixed
        public const byte RTK_BASELINE_COORDINATE_SYSTEM_NED = 1; //  RTK basestation centered, north, east, down
        public int baseline_a_mm;
        public int baseline_b_mm;
        public int baseline_c_mm;
        public uint accuracy;
        public int iar_num_hypotheses;

        public RTKBaselineMsg()
        {
            this.header = new Std.HeaderMsg();
            this.time_last_baseline_ms = 0;
            this.rtk_receiver_id = 0;
            this.wn = 0;
            this.tow = 0;
            this.rtk_health = 0;
            this.rtk_rate = 0;
            this.nsats = 0;
            this.baseline_coords_type = 0;
            this.baseline_a_mm = 0;
            this.baseline_b_mm = 0;
            this.baseline_c_mm = 0;
            this.accuracy = 0;
            this.iar_num_hypotheses = 0;
        }

        public RTKBaselineMsg(Std.HeaderMsg header, uint time_last_baseline_ms, byte rtk_receiver_id, ushort wn, uint tow, byte rtk_health, byte rtk_rate, byte nsats, byte baseline_coords_type, int baseline_a_mm, int baseline_b_mm, int baseline_c_mm, uint accuracy, int iar_num_hypotheses)
        {
            this.header = header;
            this.time_last_baseline_ms = time_last_baseline_ms;
            this.rtk_receiver_id = rtk_receiver_id;
            this.wn = wn;
            this.tow = tow;
            this.rtk_health = rtk_health;
            this.rtk_rate = rtk_rate;
            this.nsats = nsats;
            this.baseline_coords_type = baseline_coords_type;
            this.baseline_a_mm = baseline_a_mm;
            this.baseline_b_mm = baseline_b_mm;
            this.baseline_c_mm = baseline_c_mm;
            this.accuracy = accuracy;
            this.iar_num_hypotheses = iar_num_hypotheses;
        }

        public static RTKBaselineMsg Deserialize(MessageDeserializer deserializer) => new RTKBaselineMsg(deserializer);

        private RTKBaselineMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.time_last_baseline_ms);
            deserializer.Read(out this.rtk_receiver_id);
            deserializer.Read(out this.wn);
            deserializer.Read(out this.tow);
            deserializer.Read(out this.rtk_health);
            deserializer.Read(out this.rtk_rate);
            deserializer.Read(out this.nsats);
            deserializer.Read(out this.baseline_coords_type);
            deserializer.Read(out this.baseline_a_mm);
            deserializer.Read(out this.baseline_b_mm);
            deserializer.Read(out this.baseline_c_mm);
            deserializer.Read(out this.accuracy);
            deserializer.Read(out this.iar_num_hypotheses);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.time_last_baseline_ms);
            serializer.Write(this.rtk_receiver_id);
            serializer.Write(this.wn);
            serializer.Write(this.tow);
            serializer.Write(this.rtk_health);
            serializer.Write(this.rtk_rate);
            serializer.Write(this.nsats);
            serializer.Write(this.baseline_coords_type);
            serializer.Write(this.baseline_a_mm);
            serializer.Write(this.baseline_b_mm);
            serializer.Write(this.baseline_c_mm);
            serializer.Write(this.accuracy);
            serializer.Write(this.iar_num_hypotheses);
        }

        public override string ToString()
        {
            return "RTKBaselineMsg: " +
            "\nheader: " + header.ToString() +
            "\ntime_last_baseline_ms: " + time_last_baseline_ms.ToString() +
            "\nrtk_receiver_id: " + rtk_receiver_id.ToString() +
            "\nwn: " + wn.ToString() +
            "\ntow: " + tow.ToString() +
            "\nrtk_health: " + rtk_health.ToString() +
            "\nrtk_rate: " + rtk_rate.ToString() +
            "\nnsats: " + nsats.ToString() +
            "\nbaseline_coords_type: " + baseline_coords_type.ToString() +
            "\nbaseline_a_mm: " + baseline_a_mm.ToString() +
            "\nbaseline_b_mm: " + baseline_b_mm.ToString() +
            "\nbaseline_c_mm: " + baseline_c_mm.ToString() +
            "\naccuracy: " + accuracy.ToString() +
            "\niar_num_hypotheses: " + iar_num_hypotheses.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
