//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class StatusTextMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/StatusText";
        public override string RosMessageName => k_RosMessageName;

        //  STATUSTEXT message representation
        //  https://mavlink.io/en/messages/common.html#STATUSTEXT
        //  Severity levels
        public const byte EMERGENCY = 0;
        public const byte ALERT = 1;
        public const byte CRITICAL = 2;
        public const byte ERROR = 3;
        public const byte WARNING = 4;
        public const byte NOTICE = 5;
        public const byte INFO = 6;
        public const byte DEBUG = 7;
        //  Fields
        public Std.HeaderMsg header;
        public byte severity;
        public string text;

        public StatusTextMsg()
        {
            this.header = new Std.HeaderMsg();
            this.severity = 0;
            this.text = "";
        }

        public StatusTextMsg(Std.HeaderMsg header, byte severity, string text)
        {
            this.header = header;
            this.severity = severity;
            this.text = text;
        }

        public static StatusTextMsg Deserialize(MessageDeserializer deserializer) => new StatusTextMsg(deserializer);

        private StatusTextMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.severity);
            deserializer.Read(out this.text);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.severity);
            serializer.Write(this.text);
        }

        public override string ToString()
        {
            return "StatusTextMsg: " +
            "\nheader: " + header.ToString() +
            "\nseverity: " + severity.ToString() +
            "\ntext: " + text.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
