//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class TimesyncStatusMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/TimesyncStatus";
        public override string RosMessageName => k_RosMessageName;

        //  Status of the MAVLink time synchroniser
        public Std.HeaderMsg header;
        public ulong remote_timestamp_ns;
        //  remote system timestamp (nanoseconds)
        public long observed_offset_ns;
        //  raw time offset directly observed from this timesync packet (nanoseconds)
        public long estimated_offset_ns;
        //  smoothed time offset between companion system and Mavros (nanoseconds)
        public float round_trip_time_ms;
        //  round trip time of this timesync packet (milliseconds)

        public TimesyncStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.remote_timestamp_ns = 0;
            this.observed_offset_ns = 0;
            this.estimated_offset_ns = 0;
            this.round_trip_time_ms = 0.0f;
        }

        public TimesyncStatusMsg(Std.HeaderMsg header, ulong remote_timestamp_ns, long observed_offset_ns, long estimated_offset_ns, float round_trip_time_ms)
        {
            this.header = header;
            this.remote_timestamp_ns = remote_timestamp_ns;
            this.observed_offset_ns = observed_offset_ns;
            this.estimated_offset_ns = estimated_offset_ns;
            this.round_trip_time_ms = round_trip_time_ms;
        }

        public static TimesyncStatusMsg Deserialize(MessageDeserializer deserializer) => new TimesyncStatusMsg(deserializer);

        private TimesyncStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.remote_timestamp_ns);
            deserializer.Read(out this.observed_offset_ns);
            deserializer.Read(out this.estimated_offset_ns);
            deserializer.Read(out this.round_trip_time_ms);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.remote_timestamp_ns);
            serializer.Write(this.observed_offset_ns);
            serializer.Write(this.estimated_offset_ns);
            serializer.Write(this.round_trip_time_ms);
        }

        public override string ToString()
        {
            return "TimesyncStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nremote_timestamp_ns: " + remote_timestamp_ns.ToString() +
            "\nobserved_offset_ns: " + observed_offset_ns.ToString() +
            "\nestimated_offset_ns: " + estimated_offset_ns.ToString() +
            "\nround_trip_time_ms: " + round_trip_time_ms.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
